# Generated by Django 5.2.7 on 2025-12-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('TRANSFER', 'Transfer Bank'), ('EWALLET', 'E-Wallet'), ('CREDIT', 'Kartu Kredit')], default='EWALLET', max_length=20),
        ),
    ]
