# Generated by Django 5.2.7 on 2025-10-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(choices=[('BIASA', 'Biasa (2–4 hari)'), ('CEPAT', 'Cepat (1–2 hari)'), ('SAME_DAY', 'Same Day (hari ini)')], default='BIASA', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('TRANSFER', 'Transfer Bank'), ('EWALLET', 'E-Wallet'), ('CREDIT', 'Kartu Kredit')], default='EWALLET', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
