# Generated by Django 5.2.7 on 2025-10-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_insurance_order_note_order_shipping_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('TRANSFER', 'Transfer Bank'), ('EWALLET', 'E-Wallet'), ('CREDIT', 'Kartu Kredit')], default='E-WALLET', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PAID', max_length=20),
        ),
    ]
