# Generated by Django 5.2.7 on 2025-10-22 13:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('category', models.CharField(choices=[("men's shoes", "Men's Shoes"), ("women's shoes", "Women's Shoes"), ("kid's shoes", "Kid's Shoes")], default='update', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('count_sold', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
