# Generated by Django 5.2.7 on 2025-10-24 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('category', models.CharField(choices=[("Men's Shoes", "Men's Shoes"), ("Women's Shoes", "Women's Shoes"), ("Kids' Shoes", "Kids' Shoes")], default="Men's Shoes", max_length=30)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='image/products/temp/')),
                ('count_sold', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=10)),
                ('is_auction', models.BooleanField(default=False)),
                ('auction_increment', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('auction_end_time', models.DateTimeField(blank=True, null=True)),
                ('auction_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_wins', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('admin', 'Admin')], default='buyer', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
