# Generated by Django 5.2.7 on 2025-10-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_category_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[("Men's Shoes", "Men's Shoes"), ("Women's Shoes", "Women's Shoes"), ("Kids' Shoes", "Kids' Shoes")], default="Men's Shoes", max_length=30),
        ),
    ]
