# Generated by Django 5.2.7 on 2025-10-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count_sold',
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='image/products/temp/'),
        ),
    ]
